# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: write

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.13.0-rc.1"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip

                  # Checks if requirements.txt already exists, then creates it if it doesn't
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Execute AutoPep8
              run: |
                  pip install autopep8
                  autopep8 --in-place --aggressive --aggressive -r HW2/
            - name: Execute Bandit
              run: |
                  pip install bandit
                  bandit -r HW2/
            - name: Test with pytest
              run: |
                  pip install pytest pytest-cov
                  pytest --cov=HW1 HW1/tests/
            - name: Coveralls GitHub Action
              if: success() || failure()
              uses: coverallsapp/github-action@v2.3.0
